### PR TITLE
Fixed three test failures of the NMF solution

### PR DESCRIPTION
**Pull request by georghinkel**
Unfortunately, I have no idea how this pull request can be merged given that the previous one was squashed.

### CODE REVIEW

**Comment by anthonyanjorin** [comment]
Couldn't we have avoided these conflicts by you rebasing before issuing the pull request?

**Comment by georghinkel** [comment]
Unfortunately, github somehow did not let me push my rebased changes. Trying to push it to the fork, I get an error message saying that the tip of the fork is beyond my local repo, which is true because the later changes have been rebased. Perhaps there is a good way of resolving such conflicts, but I wouldn't know.

**Comment by anthonyanjorin** [comment]
I'm on it - shouldn't be a big problem as I'll just take the latest versions and overwrite what was there before.

**Comment by georghinkel** [comment]
Otherwise, I just noticed that `git push` has an option `-f` to force submit a history change. I guess that's exactly the thing I was missing and with that, I can probably repair the pull request.

**Comment by anthonyanjorin** [comment]
Please check if master is as you expect it to be.  You could also now consider working on a new branch for further changes.

**Pull request closed without merging**
