### PR TITLE
NMF Solution

### PR DESCRIPTION
**Pull request by georghinkel**
This pull request contains the current NMF solution. It passes all batch tests, all incremental forward tests except the move tests and some of the incremental backwards tests. The failures are rather due to the fact that I still do not fully understand the semantics of the configurations. For me, the results seem reasonable.

### CODE REVIEW

**Comment by anthonyanjorin** [comment]
Hi Georg,

I glanced over the files you have changed and can see that you've (I guess inadvertently) checked in some eMoflon files.  
This is my fault, I think I forgot to ignore them.

Could you please remove them (and possibly ignore them so this doesn't happen to anyone else)?

Thanks,
Tony

**Comment by georghinkel** [comment]
OK, I think these should be all of the files. Apparently, there was a TGG file in the list of unnecessarily added files, is that correct?

**Comment by anthonyanjorin** [comment]
Yes that's fine, it's a derived library file.

**Comment by anthonyanjorin** [comment]
@georghinkel Please consider creating issues for discussion with @tbuchmann and myself concerning the test cases for which you propose a different, equally reasonable result.

We had lot's of such discussions and my feeling was eventually that the behaviour expected by our tests is in a few cases an arbitrary preference of certain behaviour over other equally reasonable behaviour.  Sort of if you would simply ask your client what they want and they choose this over that.

So these tests basically check if your tool is configurable and flexible enough, or if it enforces some particular behaviour (even if it is reasonable).

**Comment by georghinkel** [comment]
Sorry for the confusion. I think I found the root of the problem: Somehow, I thought that *PREFER_CREATING_PARENT_TO_CHILD* would take precedence over *PREFER_EXISTING_FAMILY_TO_NEW* but the description clearly says that the opposite is true.

**Pull request merged**
